//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;
using System.Xml;
using System.Xml.Serialization;
using System.Collections.Generic;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ProcedureSchema.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/ProcedureSchema.xsd", IsNullable=false)]
public partial class Procedure {
    
    private ProcedureProcedure_Heading procedure_HeadingField;
    
    private List<ProcedureSection> procedure_SectionsField;
    
    private ProcedureProcedure_Redlines[] procedure_RedlinesField;

    public Procedure()
    {
        this.procedure_HeadingField = new ProcedureProcedure_Heading();
        this.procedure_SectionsField = new List<ProcedureSection>();
        this.procedure_SectionsField.Add(new ProcedureSection());

        this.procedure_RedlinesField = new ProcedureProcedure_Redlines[10];
        
    }

    /// <remarks/>
    public ProcedureProcedure_Heading Procedure_Heading {
        get {
            return this.procedure_HeadingField;
        }
        set {
            this.procedure_HeadingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Section", IsNullable=false)]
    public List<ProcedureSection> Procedure_Sections {
        get {
            return this.procedure_SectionsField;
        }
        set {
            this.procedure_SectionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Procedure_Redlines")]
    public ProcedureProcedure_Redlines[] Procedure_Redlines {
        get {
            return this.procedure_RedlinesField;
        }
        set {
            this.procedure_RedlinesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ProcedureSchema.xsd")]
public partial class ProcedureProcedure_Heading {
    
    private string nameField;
    
    private string signatureField;
    
    private string organizationField;
    
    private string dateField;
    
    private string timeField;
    
    private string load_VersionField;
    
    private string descriptionField;
    
    private string systemField;
    
    private string severityField;
    
    private ushort revisionField;
    
    public ProcedureProcedure_Heading() {
        this.nameField = "";

        this.signatureField = "";

        this.organizationField = "";

        this.dateField = "";

        this.timeField = "";

        this.load_VersionField = "";

        this.descriptionField = "";

        this.systemField = "";

        this.severityField = "";

        this.revisionField = ((ushort)(1));
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Signature {
        get {
            return this.signatureField;
        }
        set {
            this.signatureField = value;
        }
    }
    
    /// <remarks/>
    public string Organization {
        get {
            return this.organizationField;
        }
        set {
            this.organizationField = value;
        }
    }
    
    /// <remarks/>
    public string Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    public string Time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    public string Load_Version {
        get {
            return this.load_VersionField;
        }
        set {
            this.load_VersionField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string System {
        get {
            return this.systemField;
        }
        set {
            this.systemField = value;
        }
    }
    
    /// <remarks/>
    public string Severity {
        get {
            return this.severityField;
        }
        set {
            this.severityField = value;
        }
    }
    
    /// <remarks/>
    public ushort Revision {
        get {
            return this.revisionField;
        }
        set {
            this.revisionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ProcedureSchema.xsd")]
public partial class ProcedureSection {
    
    private string headingField;
    
    private string descriptionField;
    
    private List<ProcedureSectionSection_Step> section_StepField;
    
    private ushort idField;

    public ProcedureSection()
    {
        this.headingField = "";
        this.descriptionField = "";
        this.section_StepField = new List<ProcedureSectionSection_Step>();
        this.section_StepField.Add(new ProcedureSectionSection_Step());
        this.idField = ((ushort)(1));
    }


    /// <remarks/>
    public string Heading {
        get {
            return this.headingField;
        }
        set {
            this.headingField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Section_Step")]
    public List<ProcedureSectionSection_Step> Section_Step {
        get {
            return this.section_StepField;
        }
        set {
            this.section_StepField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ProcedureSchema.xsd")]
public partial class ProcedureSectionSection_Step {
    
    private string stationField;
    
    private string control_ActionField;
    
    private string expected_ResultField;
    
    private object passField;
    
    private object failField;
    
    private string commentsField;
    
    private object imageField;
    
    private ushort idField;

    public ProcedureSectionSection_Step()
    {
        this.stationField = "";
        this.stationField = "";
        this.control_ActionField = "";
        this.expected_ResultField = "";
        this.passField = "false";
        this.failField = "false";
        this.commentsField = "";
        
        this.idField = ((ushort)(1));
}


    /// <remarks/>
    public string Station {
        get {
            return this.stationField;
        }
        set {
            this.stationField = value;
        }
    }
    
    /// <remarks/>
    public string Control_Action {
        get {
            return this.control_ActionField;
        }
        set {
            this.control_ActionField = value;
        }
    }
    
    /// <remarks/>
    public string Expected_Result {
        get {
            return this.expected_ResultField;
        }
        set {
            this.expected_ResultField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: 'default' attribute supported only for primitive types.  Ignoring default='false' attribute.
    public object Pass {
        get {
            return this.passField;
        }
        set {
            this.passField = value;
        }
    }
    
    /// <remarks/>
    // CODEGEN Warning: 'default' attribute supported only for primitive types.  Ignoring default='false' attribute.
    public object Fail {
        get {
            return this.failField;
        }
        set {
            this.failField = value;
        }
    }
    
    /// <remarks/>
    public string Comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    public object Image {
        get {
            return this.imageField;
        }
        set {
            this.imageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/ProcedureSchema.xsd")]
public partial class ProcedureProcedure_Redlines {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}
